name: Pipeline CI/CD Support IA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 🛠️ AJOUT : On force le runner à utiliser Node 24 pour supprimer le warning
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code source
      uses: actions/checkout@v4

    - name: Configuration de Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Exécution des tests unitaires
      run: |
        python -m unittest test_pipeline.py